# Ubuntu 12.04 with apache and mod_wsgi
FROM ubuntu:12.04.5
USER root

MAINTAINER Martyn Gigg <martyn.gigg@gmail.com>

ENV http_proxy=http://wwwcache.rl.ac.uk:8080 http_proxy=http://wwwcache.rl.ac.uk:8080

# Install apache, mod_wsgi & git
RUN apt-get -y update && apt-get -y install libapache2-mod-wsgi git-core

# Apache config - Requires mod_rewrite
RUN a2enmod rewrite
COPY docker/etc/apache2/apache2.conf /etc/apache2/apache2.conf

# WSGI script and settings. This is referenced in httpd.conf
COPY scriptrepository_server.wsgi docker/var/www/wsgi_scripts/* /var/www/wsgi_scripts/
# Application
COPY scriptrepository_server/* /var/www/scriptrepository/application/scriptrepository_server/

# Create a fake remote and local git repository
RUN mkdir -p /var/www/scriptrepository/git && \
    git config --global user.name "Docker" && \
    git config --global user.email "a.b@domain.com"
# Setup a remote. It is left in a detached head state so that git push from the local works
RUN cd /var/www/scriptrepository/git && \
     mkdir remote && cd remote && \
     git init && \
     echo "README" > README.md && \
     git add . && \
     git commit -m"Initial commit" && \
     git checkout $(git rev-parse HEAD) && \
     chown -R www-data:www-data /var/www/scriptrepository/git/remote

# Clone to local and have apache own it
RUN cd /var/www/scriptrepository/git && \
    git clone /var/www/scriptrepository/git/remote local && \
    chown -R www-data:www-data /var/www/scriptrepository/git/local

# Run on port 80
EXPOSE 80

# Simple startup script to avoid some issues observed with container restart
ADD docker/run-httpd.sh /run-httpd.sh
RUN chmod -v +x /run-httpd.sh

CMD ["/run-httpd.sh"]
